kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: elastic-cluster
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/elastic-fleet-demo.git
  targets:
  - clusterSelector:
      matchLabels:
        elastic: enabled
  paths:
  - "./namespaces/cluster"
  - "./cluster"