kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: eck-operator
  namespace: fleet-default
spec:
  repo: ssh://git@github.com:atoy3731/elastic-fleet-demo.git
  targets:
  - clusterGroup: eck-enabled
  paths:
  - "./namespaces/operator"
  - "./operator"