apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.version }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  http:                  
    tls:
      selfSignedCertificate:
        disabled: true

  nodeSets:
  - name: master
    count: {{ .Values.count }}
    config:
      index.store.type: mmapfs
      node.roles:
      - master
      - data
      - ingest
      node.store.allow_mmap: true
      xpack.ml.enabled: false
      xpack.security.authc.token.enabled: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          resources:
            requests:
              storage: {{ .Values.persistence.size }}
          accessModes:
            - ReadWriteOnce
          {{- if .Values.persistence.storageClassName }}
          storageClassName: {{ .Values.persistence.storageClassName }}
          {{- end }}

    podTemplate:
      metadata:
        annotations:
          prometheus.istio.io/merge-metrics: "false"
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
        {{- if .Values.podAnnotations }}
          {{- toYaml .Values.podAnnotations | nindent 10 }}
        {{- end }}

      spec:
        {{- if .Values.securityContext }}
        securityContext:
        {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}

        {{- if .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml .Values.nodeSelector | nindent 10 }}
        {{- end }}
        {{- if .Values.affinity }}
        affinity:
          {{- toYaml .Values.affinity | nindent 10 }}
        {{- end }}
        {{- if .Values.tolerations }}
        tolerations:
          {{- toYaml .Values.tolerations | nindent 10 }}
        {{- end }}

        serviceAccountName: {{ include "elastic-tenant-chart.serviceAccountName" . }}
        
        {{- if .Values.updateStrategy }}
        updateStrategy:
          {{- toYaml .Values.updateStrategy | nindent 10 }}
        {{- end }}

        {{- if .Values.initContainers }}
        initContainers:
        {{ toYaml .Values.initContainers | nindent 10 }}
        {{- end }}
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms{{ .Values.heap.min }} -Xmx{{ .Values.heap.max }}"
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            lifecycle:
              {{- toYaml .Values.lifecycle | nindent 14 }}
            {{- if .Values.volumeMounts }}
            volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.volumes }}
        volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if $.Values.istio.enabled }}
        automountServiceAccountToken: true
        {{- end }}


